- hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

  tasks:
   - name: Disable swap
     command: swapoff -a

   - name: Remove Swap entry from /etc/fstab.
     lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent

   - name: Add Docker repository
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
       state: present
       filename: docker
       mode: 0600

   - name: add Kubernetes apt-key
     apt_key:
       url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
       filename: 'kubernetes'
