---
- hosts: all
  become: yes

  vars_prompt:

   - name: "new_user"
     prompt: "Account used to setup kube cluster"
     private: no

  tasks:
    - name: Setting up the user {{ new_user }}.
      user:
        name: "{{ new_user }}"
        createhome: yes
        shell: /bin/bash
        append: yes
        state: present

    - name: Creating sudo entry
      file:
        path: "/etc/sudoers.d/{{ new_user }}"
        state: touch
        mode: '0600'

    - name: "Setting up password less authenticate for {{ new_user }}."
      lineinfile:
        dest: "/etc/sudoers.d/{{ new_user }}"
        line: '{{ new_user }}  ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Copy authorized key for {{ new_user }} for user copying it from current {{ new_user }}  user.
      authorized_key:
         user: "{{ new_user }}"
         state: present
         key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - debug:
        msg: "{{ new_user_created.stdout_lines[0] }}"

